# Generated by Django 2.2.16 on 2022-05-27 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_auto_20220528_0057'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='follow',
            name='author_not_user',
        ),
    ]
